# vim:ft=toml
add_newline = false

[shell]
disabled = false
fish_indicator = "ğŸŸ"

[status]
symbol = "ğŸ”´"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[character]
success_symbol = "[ï¡](bold green) "
error_symbol = "[ï¡](bold red) "
vicmd_symbol = "[ï ](bold green) "

[jobs]
symbol = "ï™"
